---
- name: Setup redis
  hosts: all
  vars:
    redis_config_dir: "/etc/redis"
    redis_user: "root"
    redis_group: "root"
    # redis_password: "nBK46Pf7v4sqKTCF"
    # redis_port: 6379

  tasks:
    - name: Install redis
      apt:
        pkg: redis-server
        state: present
        update_cache: yes
      become: true

    - name: Checking redis server started
      service: 
        name: redis-server 
        state: started 
        enabled: yes
      become: true

    - name: changing redis configuration
      template:
        src: redis-conf.j2 
        dest: "{{ redis_config_dir }}/redis.conf"
        owner: "{{ redis_user }}" 
        group: "{{ redis_group }}" 
        mode: 0644
      become: true
      notify: Redis Restart

  handlers:

    - name: Redis Restart
      service: 
        name: redis-server 
        state: restarted 
        enabled: yes
      become: true
 